# Generated by Django 5.2.6 on 2025-10-24 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_assigned_to_alter_complaint_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_type',
            field=models.CharField(blank=True, choices=[('gps', 'GPS'), ('manual', 'Manual')], default='manual', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits starting with 1-9', regex='^[1-9][0-9]{5}$')]),
        ),
    ]
