# Generated by Django 5.2.6 on 2025-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_assigned_to_alter_complaint_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.TextField(default='Untitled complaint'),
        ),
    ]
