# Generated by Django 5.2.7 on 2025-10-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_rename_content_complaint_description_complaint_title'),
        ('complaints', '0004_alter_complaint_latitude_alter_complaint_longitude'),
    ]

    operations = [
    ]
