# Generated by Django 5.2.7 on 2025-10-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_merge_20251028_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
    ]
