# Generated by Django 5.2.7 on 2025-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
