# Generated by Django 5.2.7 on 2025-11-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_assigned'),
        ('users', '0006_remove_field_worker_assigned_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_complaints', to='users.department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to_fieldworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='users.field_worker'),
        ),
    ]
