# Generated by Django 5.2.7 on 2025-11-06 17:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_remove_complaint_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
