# Generated by Django 5.2.7 on 2025-11-07 11:27

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_fake_confidence_fake_confidence'),
        ('users', '0006_remove_field_worker_assigned_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('approved', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_images', to='complaints.complaint')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.field_worker')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
