# Generated by Django 5.2.7 on 2025-11-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_resolutionimage'),
        ('users', '0006_remove_field_worker_assigned_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolutionimage',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='resolutionimage',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='resolutionimage',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='resolutionimage',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for resolution submission', null=True),
        ),
        migrations.AddField(
            model_name='resolutionimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the resolution work done')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending_approval', max_length=20)),
                ('citizen_feedback', models.TextField(blank=True, null=True)),
                ('citizen_responded_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approve_at', models.DateTimeField(blank=True, help_text='Auto-approve after this time if no citizen response', null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='complaints.complaint')),
                ('field_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_submitted_by', to='users.field_worker')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='current_resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_complaint', to='complaints.resolution'),
        ),
        migrations.AddField(
            model_name='resolutionimage',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complaints.resolution'),
        ),
    ]
