# Generated by Django 5.2.7 on 2025-11-12 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_alter_resolutionimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['complaint', 'user'], name='idx_upvote_complaint_user'),
        ),
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['complaint'], name='idx_upvote_complaint'),
        ),
    ]
