# Generated by Django 5.2.7 on 2025-11-12 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_upvote_idx_upvote_complaint_user_and_more'),
        ('users', '0006_remove_field_worker_assigned_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['posted_by'], name='idx_complaint_posted_by'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['upvotes_count'], name='idx_complaint_upvotes_count'),
        ),
    ]
