# Generated by Django 5.2.7 on 2025-11-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_complaint_idx_complaint_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If true, hide poster identity in API responses'),
        ),
    ]
