# Generated by Django 5.2.7 on 2025-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
