# Generated by Django 5.2.7 on 2025-11-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_complaint_first_name_complaint_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='last_name',
        ),
    ]
