# Generated by Django 5.2.6 on 2025-09-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_name_ci',
        ),
    ]
