# Generated by Django 5.2.6 on 2025-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_worker',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='government_authority',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
