# Generated by Django 5.2.6 on 2025-09-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_field_worker_verified_government_authority_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field_worker',
            name='worker_name',
        ),
        migrations.RemoveField(
            model_name='government_authority',
            name='authority_name',
        ),
    ]
