# Generated by Django 5.2.6 on 2025-09-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_field_worker_worker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field_worker',
            name='assigned_area',
        ),
    ]
