# Generated by Django 5.2.7 on 2025-11-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_field_worker_assigned_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Government Authority'), ('fieldworker', 'Field Worker'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
