# Generated by Django 5.2.7 on 2025-11-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_parentuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field_worker',
            name='assigned_department',
        ),
        migrations.RemoveField(
            model_name='government_authority',
            name='assigned_department',
        ),
        migrations.AddField(
            model_name='parentuser',
            name='assigned_department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
    ]
